# Generated by Django 4.1.7 on 2023-03-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppECP', '0002_categorias_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='producto/', verbose_name='Imagen'),
        ),
    ]
