# Generated by Django 4.1.7 on 2023-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppECP', '0003_alter_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, default='producto/image_user.png', null=True, upload_to='producto/', verbose_name='Imagen'),
        ),
    ]
