# Generated by Django 4.1.7 on 2023-03-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppECP', '0004_alter_producto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='producto/')),
                ('produducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='AppECP.producto')),
            ],
        ),
    ]
