# Generated by Django 4.1.7 on 2023-03-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppECP', '0005_imageproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageproducto',
            old_name='produducto',
            new_name='producto',
        ),
    ]
