# Generated by Django 4.1.7 on 2023-03-06 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppECP', '0006_rename_produducto_imageproducto_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cesta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kart_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AppECP.kart')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppECP.producto')),
            ],
        ),
    ]
