# Generated by Django 4.1.7 on 2023-03-06 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppECP', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito_item',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carrito_item',
            name='producto',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Carrito_item',
        ),
    ]
