# Generated by Django 4.1.7 on 2023-03-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppECP', '0014_alter_producto_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'sugerencia']])),
                ('mensaje', models.TextField()),
                ('notificacion', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modificacion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='creacion',
            field=models.DateField(verbose_name='Fecha de creación'),
        ),
    ]
