# Generated by Django 4.1.7 on 2023-03-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppECP', '0015_contacto_remove_producto_modificacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProducto',
        ),
    ]
